In [2]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd

In [3]:
#import dataset
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [9]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [10]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [18]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=43)

In [19]:
stander = StandardScaler()
x_train = stander.fit_transform(x_train)
x_test = stander.transform(x_test)

In [20]:
labelEnd = LabelEncoder()
y_train = labelEnd.fit_transform(y_train)
y_test = labelEnd.transform(y_test)

In [21]:
x_train_tensor = torch.tensor(x_train.astype(np.float32))
x_test_tensor = torch.tensor(x_test.astype(np.float32))
y_train_tensor = torch.tensor(y_train.astype(np.float32))
y_test_tensor = torch.tensor(y_test.astype(np.float32))

In [50]:
class CustomDataset(Dataset):
    def __init__(self, features,labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)
    
    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [52]:
train_dataset = CustomDataset(x_train_tensor,y_train_tensor)
test_dataset = CustomDataset(x_test_tensor,y_test_tensor)

In [54]:
train_dataset.__len__()

455

In [56]:
test_dataset.__getitem__(5)

(tensor([ 0.6050, -0.8085,  0.5114,  0.4530, -0.1445, -0.7005, -0.4270, -0.0951,
         -0.3778, -0.9035, -0.6961, -1.3737, -0.8274, -0.4234,  0.1323, -0.7630,
         -0.2662,  0.4650, -0.8435, -0.5095,  0.2008, -1.2628,  0.0611,  0.0651,
          0.1309, -0.7529, -0.3863,  0.2962, -0.9809, -0.6513]),
 tensor(0.))

In [57]:
class myAnn(nn.Module):
    def __init__(self,n_number):
        super().__init__()
        self.linear = nn.Sequential(
            nn.Linear(n_number,1),
            nn.Sigmoid()
        )
    
    def forward(self,features):
        self.out = self.linear(features)
        return self.out

In [58]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_dataset = DataLoader(test_dataset,batch_size=32,shuffle=True)

In [73]:
for i,j in train_loader:
    print(i)
    print(j)

tensor([[-9.6065e-01, -9.7480e-01, -9.7714e-01, -8.4959e-01, -1.2954e+00,
         -9.9140e-01, -8.3504e-01, -1.0504e+00, -1.4910e+00, -8.5863e-01,
         -5.3798e-01,  7.4340e-02, -5.1261e-01, -4.8376e-01, -1.4804e-01,
         -4.3387e-01, -4.5653e-01, -1.0339e+00, -4.4248e-01, -6.0222e-01,
         -8.9737e-01, -7.9068e-01, -8.8148e-01, -7.7148e-01, -1.0865e+00,
         -8.3775e-01, -8.5278e-01, -1.2184e+00, -9.8091e-01, -9.0360e-01],
        [-4.8953e-01, -9.5885e-01, -5.5436e-01, -5.0971e-01, -1.2017e+00,
         -1.3142e+00, -9.8428e-01, -9.6930e-01, -9.6647e-01, -7.6319e-01,
         -1.0117e+00, -9.8945e-01, -1.0129e+00, -6.6358e-01, -1.2343e+00,
         -1.1673e+00, -1.0328e+00, -1.3527e+00, -3.8239e-01, -1.0459e+00,
         -6.4175e-01, -8.4650e-01, -7.0303e-01, -5.9591e-01, -1.2572e+00,
         -1.1116e+00, -1.0214e+00, -1.1231e+00, -1.6082e-02, -8.9594e-01],
        [-1.1243e+00, -9.9531e-01, -1.1287e+00, -9.7129e-01,  1.2029e+00,
         -4.5110e-01, -9.8042e-01, -9.2325e-01,  3.3043e+00,  9.8079e-01,
          3.7116e-01,  4.5501e-01,  2.0561e-01, -1.3623e-01,  1.7201e-01,
         -8.2224e-01, -9.8341e-01, -5.8912e-01,  2.6380e+00,  9.9197e-01,
         -1.0876e+00, -1.3122e+00, -1.1150e+00, -8.9620e-01, -2.1501e-01,
         -9.8309e-01, -1.2171e+00, -1.3428e+00,  1.0370e+00, -2.1894e-01],
        [-1.4536e-01, -8.3127e-01, -1.9612e-01, -2.3264e-01, -1.4731e-01,
         -7.1570e-01, -5.2933e-01, -3.0565e-01, -3.5636e-01, -8.9913e-01,
         -2.9041e-01, -1.0145e+00, -4.2200e-01, -2.8920e-01, -1.7352e-01,
         -7.3739e-01, -5.4410e-01, -1.0022e-01, -1.6411e-01, -8.5335e-01,
         -3.0432e-01, -1.0570e+00, -4.0090e-01, -3.5541e-01, -2.0187e-01,
         -7.9595e-01, -5.8509e-01, -3.5215e-01, -6.1167e-01, -1.0454e+00],
        [ 8.0533e-01,  2.3038e-01,  7.1562e-01,  6.8997e-01, -6.0582e-01,
         -5.9108e-01, -2.4965e-01,  1.1410e-01,  7.4612e-01, -1.5311e+00,
          6.1286e-01, -6.4855e-01,  5.8427e-01,  5.6048e-01, -6.4747e-01,
         -5.9218e-01, -4.8684e-01, -6.5749e-02,  3.2150e-01, -5.0417e-01,
          7.0797e-01, -1.0003e-01,  6.5595e-01,  5.4922e-01, -9.3319e-01,
         -6.7606e-01, -3.9350e-01, -9.2980e-02,  5.8433e-01, -1.0678e+00],
        [ 5.6554e-01,  5.2199e-01,  5.7265e-01,  4.2496e-01,  3.1543e-01,
          4.3256e-01,  1.8388e-01,  1.7053e-01,  1.2242e+00, -5.6508e-01,
          8.5950e-02,  1.2334e-01, -1.7583e-02,  5.0301e-02, -7.0076e-01,
         -3.3649e-01, -3.7191e-01, -4.1024e-01, -6.0925e-01, -5.9645e-01,
          6.4048e-01,  9.5746e-01,  6.4712e-01,  4.8909e-01,  3.1049e-01,
          2.8854e-01,  1.1548e-01,  2.2912e-01,  9.1343e-01, -4.3840e-01],
        [ 1.3674e-01, -9.1329e-01,  1.4660e-01, -1.7836e-02,  1.1888e+00,
          5.3426e-01,  1.2607e-01,  5.3765e-01,  1.0672e+00,  9.2890e-02,
          3.5631e-01, -8.7129e-01,  4.4501e-01,  3.1360e-02, -4.9192e-01,
          1.0644e+00,  5.6144e-01,  7.9591e-01,  4.8460e-01,  4.9858e-01,
          3.9058e-04, -1.1862e+00,  4.9343e-02, -1.4892e-01, -2.0625e-01,
          3.0944e-01, -7.0824e-02,  3.5587e-01,  3.8526e-01,  2.8987e-02],
        [ 1.7060e-01, -1.0272e+00,  1.0984e-01,  2.9276e-02, -5.3328e-01,
         -5.0306e-01, -5.4141e-01, -3.5701e-01, -1.0557e+00, -5.3471e-01,
         -2.2619e-01, -1.5103e+00, -1.6399e-01, -2.5070e-01, -7.4875e-01,
         -5.9047e-01, -5.2515e-01, -1.6226e-01,  1.6086e-01, -4.1454e-01,
          1.9058e-01, -1.2357e+00,  1.9069e-01, -1.6306e-02, -4.5586e-01,
         -3.5453e-01, -2.8834e-01,  1.3816e-01,  3.1784e-01, -1.2754e-01],
        [ 1.0987e+00, -7.0597e-01,  1.1445e+00,  9.7516e-01,  7.1689e-01,
          2.0265e+00,  9.8242e-01,  1.4829e+00,  1.1957e+00,  5.6576e-01,
          1.9761e+00, -1.2231e+00,  1.6358e+00,  1.9263e+00,  3.1301e-01,
          1.8770e+00,  6.5490e-01,  1.5662e+00,  6.8571e-01,  1.4805e+00,
          1.2376e+00, -1.0794e+00,  1.2478e+00,  1.2364e+00,  6.7396e-01,
          1.8741e+00,  4.9674e-01,  1.4072e+00,  1.3485e+00,  1.4558e+00],
        [-8.3299e-02, -5.2827e-01, -4.9880e-02, -2.2255e-01,  4.4221e-01,
          8.6339e-01,  1.1798e-01,  1.6774e-01,  1.0316e+00,  9.1716e-01,
         -5.2486e-01, -1.0462e-02, -4.5204e-01, -3.8185e-01, -3.4232e-01,
          5.0972e-01,  3.3958e-01,  4.7193e-01, -1.1383e-01,  3.7390e-01,
         -1.2027e-01,  1.9983e-01, -9.7892e-02, -2.4083e-01,  5.9513e-01,
          1.0970e+00,  9.0488e-01,  7.3911e-01,  1.1542e+00,  1.1876e+00],
        [ 1.2708e+00, -4.8498e-01,  1.1935e+00,  1.1743e+00,  6.3942e-01,
          9.2336e-02,  6.9963e-01,  9.4272e-01,  5.3205e-01, -9.9440e-02,
          1.0514e+00,  7.1883e-01,  9.6054e-01,  1.0136e+00,  3.6663e-01,
         -2.5164e-01,  1.0087e-01,  7.5800e-01,  1.6155e-02,  3.7834e-01,
          1.2090e+00, -1.2396e-01,  1.1094e+00,  1.1316e+00,  7.8343e-01,
         -1.8116e-01,  2.4993e-01,  7.6894e-01, -2.7320e-02,  1.9683e-02],
        [-6.6161e-01, -4.2347e-01, -6.9079e-01, -6.4319e-01,  3.0839e-01,
         -9.1318e-01, -8.2233e-01, -8.5671e-01, -3.5279e-01, -7.2559e-01,
         -7.6795e-01,  1.3690e+00, -8.9174e-01, -5.5108e-01,  2.7693e-01,
         -9.4831e-01, -6.5103e-01, -9.2569e-01,  1.3577e+00, -7.6728e-01,
         -7.7058e-01,  1.2805e-01, -8.2906e-01, -6.8851e-01,  1.3970e-01,
         -9.7485e-01, -8.9849e-01, -1.0852e+00,  4.6392e-01, -1.0092e+00],
        [ 1.7306e+00, -1.1183e+00,  1.7532e+00,  1.7912e+00,  2.8021e-01,
          5.1392e-01,  1.3512e+00,  1.3893e+00, -2.8112e-02, -5.7665e-01,
          1.2047e+00, -7.8819e-01,  1.2195e+00,  1.0954e+00,  1.4880e+00,
         -4.6641e-02,  1.0885e+00,  1.2474e+00, -3.3824e-01,  6.2015e-01,
          1.2683e+00, -1.4367e+00,  1.3097e+00,  1.1762e+00,  2.1852e-01,
         -3.2932e-01,  5.9949e-01,  6.9587e-01, -8.7817e-01, -4.0611e-01],
        [ 9.3228e-01,  4.5635e+00,  8.6676e-01,  7.3568e-01,  1.2667e-01,
          4.5845e-01,  6.4979e-01,  9.7966e-01, -2.8112e-02, -4.5662e-01,
          4.4298e-01, -6.4723e-01,  5.7768e-02,  1.5983e-01, -7.0639e-01,
          1.3786e-01, -2.1067e-01,  3.6680e-01, -9.8817e-01, -4.2519e-01,
          1.2622e+00,  3.0613e+00,  9.8576e-01,  8.8935e-01,  1.7911e-01,
          7.0659e-01,  2.3504e-01,  1.3535e+00, -9.3140e-02,  4.1575e-02],
        [-1.1497e+00, -9.4291e-01, -1.1610e+00, -9.5559e-01, -2.5718e-01,
         -1.0735e+00, -1.0956e+00, -1.1888e+00, -4.0631e-01, -3.3804e-01,
          5.5910e-02,  1.2899e-01, -9.5794e-02, -3.0485e-01,  2.4478e+00,
         -7.6472e-01, -1.2389e+00, -1.5868e+00,  6.2071e-01, -1.0972e-01,
         -9.1373e-01, -7.1730e-01, -9.5215e-01, -7.7869e-01,  8.6226e-01,
         -9.6317e-01, -1.2880e+00, -1.5720e+00,  3.5290e-02, -3.9571e-01],
        [-8.7884e-01, -9.8391e-01, -8.7869e-01, -8.0079e-01, -1.1587e+00,
         -6.3268e-01, -6.7371e-01, -7.2489e-01,  6.6406e-01, -5.1719e-02,
         -8.4287e-01, -3.1763e-01, -7.6298e-01, -6.0852e-01, -5.6208e-01,
         -3.6440e-01, -5.8073e-01, -8.0161e-01, -1.8618e-01, -7.8813e-01,
         -8.6874e-01, -7.7313e-01, -8.2435e-01, -7.6134e-01, -1.0033e+00,
         -3.7113e-01, -5.7548e-01, -7.2018e-01,  4.6713e-01, -6.2010e-01],
        [-7.2086e-01, -1.4601e+00, -7.2878e-01, -6.8890e-01, -4.5721e-01,
         -5.5021e-01, -5.9274e-01, -4.0205e-01, -7.0245e-01,  4.3417e-01,
         -6.1049e-01, -1.2446e+00, -6.7046e-01, -5.2473e-01, -2.7844e-01,
         -6.9069e-01, -5.9336e-01, -8.1471e-01, -4.6700e-01, -5.1748e-01,
         -6.7038e-01, -1.3585e+00, -7.2924e-01, -6.4900e-01,  4.6814e-01,
         -4.5166e-01, -3.9830e-01, -4.6742e-01, -2.2317e-01,  1.8387e-01],
        [ 1.8548e+00,  2.7045e+00,  1.7777e+00,  2.1333e+00, -1.1491e-01,
          1.7185e-01,  5.8751e-01,  9.3792e-01, -1.7083e-01, -8.7888e-01,
          2.6369e+00,  7.8667e-01,  2.3216e+00,  3.2625e+00, -8.0866e-01,
         -6.0641e-01, -4.0391e-01, -4.0180e-01, -8.1527e-01, -6.2929e-01,
          3.3031e+00,  3.4265e+00,  3.1295e+00,  4.3663e+00,  3.3676e-01,
          3.5862e-02,  3.3156e-01,  7.4657e-01, -6.9059e-02, -1.1057e-01],
        [ 3.9367e+00, -1.7743e-01,  3.9345e+00,  5.1620e+00,  1.2592e+00,
          8.6154e-01,  2.8723e+00,  2.7859e+00, -6.0255e-01, -1.0943e+00,
          8.5103e+00,  5.2096e-01,  9.1084e+00,  9.9722e+00,  2.1367e+00,
          1.3046e-01,  1.3837e+00,  4.2367e-01,  3.3737e+00,  3.3663e-01,
          2.4074e+00, -1.1496e+00,  2.3786e+00,  2.7635e+00, -7.9744e-01,
         -6.5762e-01,  2.1584e-01,  6.5113e-01, -2.0276e+00, -1.5844e+00],
        [-5.2338e-01, -5.2124e-02, -5.8418e-01, -5.4364e-01, -9.2911e-01,
         -1.1647e+00, -1.0188e+00, -1.0337e+00, -9.9145e-01, -4.8699e-01,
         -7.7451e-01,  6.2649e-01, -8.0209e-01, -5.7641e-01,  2.9348e-01,
         -9.6790e-01, -1.0112e+00, -8.7709e-01, -1.1383e-01, -6.6345e-01,
         -6.1107e-01,  4.4387e-01, -6.8300e-01, -5.9437e-01, -4.4710e-01,
         -1.0331e+00, -1.1474e+00, -1.1334e+00, -5.7315e-01, -6.6389e-01],
        [-8.1395e-01, -1.4327e+00, -7.7698e-01, -7.6266e-01,  1.9283e+00,
          1.1268e-01, -1.3130e-01,  1.5459e-01,  7.1758e-01,  9.1427e-01,
         -5.2521e-01, -4.0281e-01, -5.1118e-01, -5.1876e-01, -1.1891e-01,
         -4.3615e-01, -4.2159e-01,  4.9067e-03,  9.3411e-02,  1.6431e-03,
         -7.1537e-01, -8.2098e-01, -6.7123e-01, -7.1153e-01,  1.2520e+00,
         -9.6317e-02, -2.4224e-01,  2.3807e-01,  6.9349e-01,  4.3508e-01],
        [-1.3787e+00, -1.4532e+00, -1.2537e+00, -1.1485e+00,  4.7245e+00,
          2.1984e+00,  9.6673e-02,  7.9187e-02,  2.0020e+00,  4.6567e+00,
         -2.4436e-03, -2.0079e-01,  6.3491e-02, -4.3641e-01,  9.2299e-01,
          1.1384e+00,  1.6023e-01,  1.7696e+00,  6.2562e-01,  2.9873e+00,
         -1.2389e+00, -1.4829e+00, -1.1388e+00, -1.0137e+00,  2.5307e+00,
          5.2585e-01, -3.1331e-01, -1.9886e-01,  2.0385e-01,  2.2439e+00],
        [ 8.2508e-01,  1.8001e+00,  7.7689e-01,  7.6456e-01,  1.8724e-01,
          1.1083e-01,  1.3903e-01,  3.7749e-01, -8.5199e-02, -1.1060e-03,
          1.7982e+00, -8.9610e-02,  1.5118e+00,  1.5228e+00,  5.7779e-01,
         -1.8445e-01, -1.6057e-01,  5.1156e-01,  1.6155e-02,  3.1045e-01,
          1.3542e+00,  1.4057e+00,  1.3067e+00,  1.3016e+00,  1.2082e+00,
         -8.7096e-02, -5.4019e-02,  5.9148e-01,  1.5890e-01,  3.5025e-01],
        [ 1.2680e+00, -3.7563e-01,  1.2875e+00,  1.1715e+00,  9.5636e-01,
          1.1759e+00,  1.3437e+00,  1.3033e+00,  3.2154e-01, -3.3660e-01,
          7.6168e-01, -1.0106e+00,  6.7345e-01,  6.2430e-01, -2.3177e-01,
          8.2633e-01,  1.0321e+00,  9.1999e-01,  4.8582e-01, -8.0884e-02,
          1.3256e+00, -6.9497e-01,  1.2626e+00,  1.1625e+00,  1.5542e+00,
          1.5396e+00,  2.2057e+00,  1.8187e+00,  1.4255e+00,  4.1866e-01],
        [-1.0820e+00, -6.6041e-01, -1.0976e+00, -9.3484e-01, -1.3956e-01,
         -1.0182e+00, -9.8939e-01, -1.1106e+00,  2.4305e-01, -1.1679e-01,
         -6.8335e-01, -4.3824e-01, -7.2721e-01, -5.8197e-01,  3.0358e-02,
         -1.0354e+00, -8.8005e-01, -1.0541e+00, -5.7859e-01, -4.9307e-01,
         -1.0405e+00, -6.2320e-01, -1.0779e+00, -8.6819e-01, -1.7122e-01,
         -1.0460e+00, -1.1107e+00, -1.3723e+00, -3.6926e-01, -5.5881e-01],
        [ 1.4796e+00, -2.4349e-01,  1.4305e+00,  1.3650e+00,  5.1968e-01,
          7.2471e-01,  9.1016e-01,  1.1449e+00,  2.7159e-01, -5.6363e-01,
          2.1612e-01, -3.8529e-01,  1.0555e-02,  2.4548e-01, -4.4359e-01,
         -1.9584e-01, -1.8272e-02,  5.8222e-01, -5.0134e-01, -7.7748e-01,
          1.5239e+00,  4.7417e-01,  1.3156e+00,  1.2673e+00,  8.4912e-01,
          7.1520e-01,  7.5122e-01,  1.6309e+00,  1.0900e+00, -3.4646e-01],
        [ 2.5713e+00,  6.3590e-01,  2.4476e+00,  2.8821e+00, -8.4036e-01,
          1.7554e-01,  5.3394e-01,  1.2051e+00, -5.6655e-02, -1.0539e+00,
          8.8356e-01, -6.4723e-01,  8.2129e-01,  1.1656e+00, -6.8984e-01,
          6.2402e-04, -1.1805e-01,  7.9591e-01, -9.2984e-02,  1.0073e-02,
          2.3869e+00,  4.0559e-01,  2.2520e+00,  2.5986e+00, -4.2083e-01,
          6.1315e-01,  5.7452e-01,  1.7710e+00,  1.0884e+00,  4.1976e-01],
        [-5.9955e-01, -3.0045e-01, -6.5729e-01, -5.9524e-01, -1.3728e+00,
         -1.2220e+00, -1.0962e+00, -1.1082e+00, -1.5516e+00, -3.0623e-01,
         -6.0359e-01, -5.4622e-01, -6.7475e-01, -4.9961e-01, -7.4974e-01,
         -1.0559e+00, -1.2563e+00, -1.3202e+00, -6.9386e-01, -8.7066e-01,
         -6.6833e-01, -5.4664e-01, -7.3571e-01, -6.3027e-01, -1.3623e+00,
         -1.1353e+00, -1.2841e+00, -1.3104e+00, -1.1880e+00, -7.5693e-01],
        [-5.3185e-01,  2.4425e+00, -6.0297e-01, -5.4084e-01, -1.3616e+00,
         -1.3133e+00, -1.1155e+00, -1.2496e+00, -4.1345e-01, -4.6530e-01,
          1.2842e-01,  4.6122e+00,  1.4935e-03, -1.2573e-01,  1.1409e-01,
         -9.7867e-01, -1.3061e+00, -2.0010e+00,  1.3602e+00, -2.5792e-01,
         -5.9062e-01,  1.9735e+00, -6.6681e-01, -5.6929e-01, -1.6724e+00,
         -1.2691e+00, -1.3212e+00, -1.7273e+00, -8.0592e-01, -9.1783e-01],
        [-4.8671e-01, -5.1232e-01, -5.5477e-01, -5.0747e-01, -1.4616e+00,
         -1.3030e+00, -9.4828e-01, -8.1977e-01, -1.2305e+00, -1.0423e+00,
         -1.0534e-01,  1.8853e+00, -1.8784e-01, -2.0746e-01,  1.2005e-01,
         -8.3363e-01, -8.8683e-01, -7.0919e-02,  1.7182e+00, -3.3556e-01,
         -7.0310e-01, -8.7202e-01, -7.6457e-01, -6.4315e-01, -2.1160e+00,
         -1.2999e+00, -1.2138e+00, -1.3050e+00, -1.6215e+00, -1.3617e+00],
        [-1.5947e-01, -3.2095e-01, -2.4268e-01, -2.4106e-01, -1.1862e+00,
         -1.1924e+00, -8.6668e-01, -9.3641e-01, -8.7014e-01, -1.1016e+00,
         -5.1899e-01, -6.3227e-02, -5.7127e-01, -3.9152e-01, -1.0767e+00,
         -1.1477e+00, -8.5774e-01, -1.1318e+00, -8.4347e-01, -1.1497e+00,
         -1.7139e-01,  6.7443e-02, -2.5956e-01, -2.5973e-01, -1.2003e+00,
         -1.1210e+00, -8.1221e-01, -9.5415e-01, -9.2472e-01, -1.1805e+00],
        [ 5.4015e-01,  9.1404e-02,  4.8687e-01,  4.4711e-01, -3.2691e-01,
         -3.8398e-01,  1.0153e-01,  4.2986e-01, -6.7359e-02, -1.2881e+00,
          1.1708e+00, -3.4590e-01,  1.0244e+00,  7.8263e-01,  1.2662e+00,
         -1.9356e-01,  1.6739e-01,  1.1164e+00, -5.9086e-01, -7.8502e-01,
          7.0183e-01, -1.7819e-01,  6.2061e-01,  5.7155e-01,  7.7030e-01,
         -3.3240e-01,  3.7213e-02,  5.3929e-01, -4.1903e-01, -1.1127e+00]])
tensor([0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
        1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1.])
tensor([[-8.6755e-01, -1.0340e+00, -8.9748e-01, -8.0079e-01,  3.0134e-01,
         -8.7971e-01, -8.2109e-01, -5.9611e-01, -8.9511e-01,  5.5998e-01,
         -6.9405e-01,  1.1410e+00, -7.1720e-01, -4.5617e-01,  2.6364e+00,
         -2.4026e-01, -6.9439e-01,  7.2698e-01,  1.2878e+00,  4.7373e-01,
         -1.0201e+00, -1.4127e+00, -1.0517e+00, -8.4827e-01, -4.7338e-01,
         -1.0831e+00, -1.1321e+00, -1.0852e+00, -1.6198e+00, -6.0587e-01],
        [-1.4543e+00, -1.1047e+00, -1.4632e+00, -1.1553e+00, -1.8504e+00,
         -1.3655e+00, -1.0696e+00, -1.1618e+00, -1.0304e-01,  7.9713e-01,
         -8.0696e-01,  1.9872e-01, -8.2832e-01, -6.4746e-01,  1.3064e-01,
         -1.1700e+00, -1.1511e+00, -1.4027e+00,  8.2060e-01, -6.9407e-01,
         -1.3577e+00, -8.9435e-01, -1.3788e+00, -1.0390e+00, -1.4801e+00,
         -1.2680e+00, -1.2505e+00, -1.5202e+00,  1.2840e-01, -3.3715e-01],
        [-1.8768e-01,  6.9513e-01, -2.1532e-01, -2.7275e-01, -6.1991e-01,
         -5.1822e-01, -5.2360e-01, -3.9344e-01, -2.8112e-02, -8.1525e-01,
         -6.0255e-01,  2.8917e-01, -5.4647e-01, -4.3311e-01, -8.4043e-01,
         -6.6108e-01, -4.2411e-01,  3.9373e-02, -4.7926e-01, -7.8147e-01,
         -2.4297e-01,  9.7979e-01, -2.5691e-01, -3.2896e-01, -7.0985e-01,
         -5.3773e-01, -2.2544e-01,  1.8439e-01, -6.4243e-02, -8.2260e-01],
        [-8.7319e-01, -9.7708e-01, -8.4520e-01, -7.9743e-01,  4.9151e-01,
         -2.5954e-01, -4.4312e-01, -4.0432e-01, -1.4585e-01,  9.0414e-01,
         -8.5703e-01, -7.1055e-01, -7.2769e-01, -6.2664e-01,  1.3958e-01,
         -3.7920e-01, -1.4499e-01, -2.6048e-01,  3.8772e-01, -3.5509e-01,
         -9.0351e-01, -9.2147e-01, -8.2347e-01, -7.7354e-01,  4.1121e-01,
         -2.3096e-01, -2.1728e-01, -1.2430e-01,  6.2607e-01,  3.6120e-01],
        [-8.1677e-01,  1.3241e-01, -8.5296e-01, -7.5761e-01, -7.8965e-01,
         -1.1256e+00, -1.0523e+00, -1.1063e+00, -6.4179e-01,  8.8551e-02,
         -9.4577e-01, -2.1964e-01, -9.0596e-01, -6.5687e-01, -9.2483e-01,
         -1.1121e+00, -1.1442e+00, -1.3005e+00, -6.6811e-01, -6.3106e-01,
         -9.0146e-01,  1.2008e-01, -9.2300e-01, -7.8058e-01, -9.4633e-01,
         -1.1148e+00, -1.1996e+00, -1.3050e+00, -5.6833e-01, -4.4169e-01],
        [-7.8574e-01, -8.1740e-02, -8.1742e-01, -7.3545e-01, -6.4738e-01,
         -1.0156e+00, -8.1660e-01, -6.9984e-01,  6.9974e-01, -4.7253e-01,
         -4.9275e-01,  1.4594e+00, -4.4203e-01, -4.8891e-01, -1.5101e-01,
         -6.5368e-01, -7.2681e-01, -2.9082e-01,  1.6974e+00, -3.5021e-01,
         -8.1353e-01,  7.3823e-02, -8.3731e-01, -7.4039e-01, -9.0253e-01,
         -9.9280e-01, -9.5966e-01, -8.0235e-01,  5.7148e-01, -7.8046e-01],
        [ 3.1729e-01,  7.2019e-01,  2.7527e-01,  1.4678e-01, -4.0509e-01,
          3.5815e-03, -4.4586e-01, -4.2406e-01, -3.2068e-01,  5.0953e-02,
         -7.0062e-01, -1.3266e+00, -7.3294e-01, -4.4691e-01, -1.2260e+00,
         -6.5368e-01, -5.5925e-01, -9.6550e-01, -1.0544e+00, -5.0683e-01,
          2.9896e-01,  3.7528e-01,  1.7891e-01,  1.4225e-01, -1.0115e-01,
          4.3855e-01,  4.2183e-01,  1.0088e-01,  4.2379e-01,  7.3992e-01],
        [ 2.8478e+00,  2.1671e-01,  3.0235e+00,  3.0924e+00,  3.4074e+00,
          3.3596e+00,  4.2015e+00,  3.8410e+00,  2.9903e+00,  8.6076e-01,
          3.8006e+00,  3.6191e+00,  3.3031e+00,  3.9481e+00,  5.4067e+00,
          4.1360e+00,  4.0743e+00,  1.1389e+00,  3.0843e+00,  2.7321e+00,
          1.9800e+00, -2.6911e-01,  2.1548e+00,  2.0317e+00,  1.6286e+00,
          1.0195e+00,  1.4652e+00,  1.6249e+00,  4.9924e-01, -2.2496e-01],
        [-9.0423e-01,  4.7870e-01, -8.2845e-01, -8.0528e-01,  1.8579e+00,
          3.1053e-01,  1.8512e-01,  1.8469e-01,  2.7873e-01,  8.5064e-01,
         -5.9289e-01,  4.3051e-01, -5.0498e-01, -4.9961e-01,  3.5405e-01,
         -4.4355e-01, -2.1361e-01, -2.1396e-01, -8.2753e-01, -3.0051e-01,
         -7.1537e-01,  1.5412e+00, -6.0379e-01, -6.4642e-01,  2.5614e+00,
          6.9060e-02,  6.1054e-01,  3.9614e-01,  8.5056e-02,  6.4907e-01],
        [-4.1618e-01,  1.0460e+00, -3.8770e-01, -4.4661e-01,  1.1184e+00,
          3.9188e-01,  2.8977e-01,  4.8932e-01,  3.1441e-01,  4.4573e-01,
          5.9363e-02, -4.0613e-02,  2.2000e-02, -9.8346e-02,  2.6038e-01,
          5.9847e-02, -5.4478e-02,  2.2205e-01, -4.8662e-01, -5.1600e-02,
          1.5377e-01,  1.2430e+00,  1.2002e-01, -3.4218e-03,  2.3074e+00,
          9.0702e-01,  6.1102e-01,  8.3157e-01,  7.5771e-01,  1.0344e+00],
        [-3.6258e-01, -6.9230e-01, -4.0036e-01, -4.0960e-01, -1.4590e-01,
         -7.9170e-01, -6.2961e-01, -8.4102e-01,  6.8904e-01, -7.4150e-01,
         -6.0014e-01,  3.6651e-02, -6.3660e-01, -4.7347e-01, -4.8861e-01,
         -2.0780e-01, -2.1614e-01, -9.1018e-01,  6.8816e-01, -6.9229e-01,
         -4.9859e-01, -3.2493e-01, -5.4343e-01, -5.0298e-01, -2.9821e-01,
         -4.7810e-01, -3.6469e-01, -8.6543e-01,  1.1125e+00, -7.4325e-01],
        [ 1.5162e+00,  3.0121e+00,  1.4631e+00,  1.5837e+00, -8.5375e-01,
          1.4781e-01,  3.1095e-01,  4.2961e-01, -1.3875e+00, -1.4009e+00,
          1.1425e+00,  2.2887e-01,  8.7804e-01,  1.4137e+00, -4.8166e-01,
          5.7569e-02, -1.8457e-01, -1.4330e-01, -8.5819e-01, -6.4837e-01,
          2.3644e+00,  3.1474e+00,  2.1342e+00,  2.7258e+00,  3.6742e-01,
          9.2915e-01,  5.9709e-01,  6.9587e-01, -3.1789e-01, -4.6631e-01],
        [ 2.6651e-01, -6.5129e-01,  3.0223e-01,  4.5540e-02,  1.3156e+00,
          1.3996e+00,  3.0222e-01,  9.0958e-01,  6.5693e-01,  2.6787e-01,
          7.8008e-02, -2.4791e-01, -4.0474e-02, -2.8758e-02,  6.6582e-01,

In [59]:
learing_rate =0.1
epochs =45

In [68]:
#create a model
model = myAnn(x_train.shape[1])
# create optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learing_rate)

In [69]:
loss_function = nn.BCELoss()

In [85]:
#traing loop
for i in range(epochs):
    for batch_features,batch_labels in train_dataset:
        #predict the result
        y_pred = model(batch_features)

        #calculate losss
        loss = loss_function(y_pred.view(-1,1),batch_labels.view(-1,1))

        #clear grad
        optimizer.zero_grad()

        #backpropogation

        loss.backward()

        #update the perameters

        optimizer.step()

    print(f"epochs : {i+1} , loss:  {loss.item()}" )
    print("-"*15)

epochs : 1 , loss:  0.0003685931151267141
---------------
epochs : 2 , loss:  6.485779886133969e-05
---------------
epochs : 3 , loss:  2.06419535970781e-05
---------------
epochs : 4 , loss:  9.069810403161682e-06
---------------
epochs : 5 , loss:  4.701651505456539e-06
---------------
epochs : 6 , loss:  2.7787750696006697e-06
---------------
epochs : 7 , loss:  1.8031197441814584e-06
---------------
epochs : 8 , loss:  1.2475017001634114e-06
---------------
epochs : 9 , loss:  9.04080877717206e-07
---------------
epochs : 10 , loss:  6.792810722799913e-07
---------------
epochs : 11 , loss:  5.252568371361122e-07
---------------
epochs : 12 , loss:  4.157521971137612e-07
---------------
epochs : 13 , loss:  3.3552188938301697e-07
---------------
epochs : 14 , loss:  2.752418311047222e-07
---------------
epochs : 15 , loss:  2.2897064866356232e-07
---------------
epochs : 16 , loss:  1.9279295315755007e-07
---------------
epochs : 17 , loss:  1.6404874259023927e-07
---------------
epochs : 18 , loss:  1.4088820421420678e-07
---------------
epochs : 19 , loss:  1.2199105015042733e-07
---------------
epochs : 20 , loss:  1.064011598828074e-07
---------------
epochs : 21 , loss:  9.341013651464891e-08
---------------
epochs : 22 , loss:  8.248731120374941e-08
---------------
epochs : 23 , loss:  7.322775275042659e-08
---------------
epochs : 24 , loss:  6.531983132163077e-08
---------------
epochs : 25 , loss:  5.852027129549242e-08
---------------
epochs : 26 , loss:  5.263754232487372e-08
---------------
epochs : 27 , loss:  4.751851534479101e-08
---------------
epochs : 28 , loss:  4.3040571995334176e-08
---------------
epochs : 29 , loss:  3.910429313691566e-08
---------------
epochs : 30 , loss:  3.5628708872081916e-08
---------------
epochs : 31 , loss:  3.254709213251772e-08
---------------
epochs : 32 , loss:  2.9804120060816786e-08
---------------
epochs : 33 , loss:  2.7353925347028962e-08
---------------
epochs : 34 , loss:  2.5157691041499675e-08
---------------
epochs : 35 , loss:  2.3182717967529243e-08
---------------
epochs : 36 , loss:  2.1401858063541113e-08
---------------
epochs : 37 , loss:  1.9791556837844837e-08
---------------
epochs : 38 , loss:  1.833169349652053e-08
---------------
epochs : 39 , loss:  1.7004989416591343e-08
---------------
epochs : 40 , loss:  1.5796670638223986e-08
---------------
epochs : 41 , loss:  1.469370403128778e-08
---------------
epochs : 42 , loss:  1.3684915423084476e-08
---------------
epochs : 43 , loss:  1.2760561496349965e-08
---------------
epochs : 44 , loss:  1.1912063335728362e-08
---------------
epochs : 45 , loss:  1.113180658762758e-08
---------------